### ISSUE TITLE
fazer o blur do personagem por meio de CSS e colocar transição quando confirmar resposta

### ISSUE THREAD

**Issue by LeoBardineo** [Hartye/adivinhe-personagem#1]
como sugestão, sugiro fazer a imagem ficar com o blur por meio do [filter: blur()](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/blur), e quando acertar ou errar, fazer a transition deixar o blur como 0
seria legal também deixar os personagens com e sem o blur no final, lado a lado, além do nome do personagem

**Comment by Hartye** [comment]
Achei uma ótima ideia. Vou começar a trabalhar nisso e adicionar umas coisinhas!

**Comment by Hartye** [comment]
Já tinham me recomendando fazer algo assim mas eu acho que não funcionaria pelo fato de que eu preciso ajustar manualmente a intensidade do blur e onde o blur se foca, algo assim é extremamente mais fácil de fazer diretamente na imagem.

Porém, dito isso acho que seria interessante ter uma segunda imagem limpa pra mostrar no fim, junto com as outras respostas.
